language: node_js
node_js:
 - "node"

cache: npm

before_install: cd cliente

script:
 - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: cliente/dist
 on:
   branch: master