language: node_js
node_js:
 - "node"

cache: npm

script: 
 - cd cliente
 - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: cliente/dist
 on:
   branch: master